- name: Deploy Portfolio
  hosts: all
  become: true

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy Portfolio Files
      copy:
        src: ../portfolio/
        dest: /var/www/html/
        mode: '0644'
